name: Hello github actions
on: push

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
      - run: echo "Github actions"
  goodbye-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Goodbye"
      - run: echo "Github actions"
      - run: EXPORT MY_VAR=123
      - run: echo $MY_VAR
